FROM debian:buster
RUN apt update  && apt upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends     build-essential     git     libblas-dev     liblapack-dev     libmumps-dev     libscotchparmetis-dev libmetis-dev    libhypre-dev     gfortran     mpich     sudo     cmake     ca-certificates     less
ADD .stamp ./
ADD precaches/opts-debian-buster.cmake /opts-debian-buster.cmake
RUN ls
RUN mkdir elmerbuild
WORKDIR elmerbuild
