FROM debian:stretch
RUN apt-get -y update && apt-get install -y gcc cmake g++ gfortran libopenblas-dev git
RUN apt-get install -y unzip libopenmpi-dev
RUN apt-get install -y libmumps-dev libhypre-dev
RUN apt-get install -y libscotchparmetis-dev
RUN apt-get install -y libmetis-dev
RUN apt-get install -y libhypre-dev
ADD ./precaches/opts-debian-stretch-nogui.cmake /opts-debian-stretch-nogui.cmake
RUN ls
RUN mkdir elmerbuild
WORKDIR elmerbuild
