FROM ubuntu:focal
# Create an apt configuration file to fix erroneous "hash sum mismatch" errors
RUN printf "Acquire::http::Pipeline-Depth 0;\nAcquire::http::No-Cache true;\nAcquire::BrokenProxy true;" \
    >> /etc/apt/apt.conf.d/99fixbadproxy
# Add the necessary packages to compile Elmer/Ice
RUN apt update -o Acquire::CompressionTypes::Order::=gz && apt upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    build-essential \
    git \
    libblas-dev \
    liblapack-dev \
    libmumps-dev \
    libparmetis-dev \
    libhypre-dev \
    gfortran \
    mpich \
    sudo \
    cmake \
    ca-certificates \
    less
ADD .stamp ./
ADD precaches/opts-ubuntu-focal.cmake /opts-ubuntu-focal.cmake
RUN ls
RUN mkdir elmerbuild
WORKDIR elmerbuild
