FROM ubuntu:trusty
RUN apt-get -y update && apt-get install -y gcc cmake g++ gfortran libopenblas-dev git
RUN apt-get install -y unzip libopenmpi-dev
RUN apt-get install -y libparmetis-dev 
RUN apt-get install -y libmetis-dev 
RUN apt-get install -y software-properties-common
#RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
#RUN apt-get update
#RUN apt-get install -y g++-4.9 gcc-4.9 gfortran-4.9
ADD .stamp ./
ADD precaches/opts-ubuntu-trusty.cmake /opts-ubuntu-trusty.cmake
RUN ls
RUN mkdir elmerbuild
WORKDIR elmerbuild
